name: Bundle Size Check

on:
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - 'rollup.config.js'
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'rollup.config.js'

jobs:
  size-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Check bundle size
        run: npm run size
      
      - name: Generate bundle report
        run: |
          ANALYZE=true npm run build > bundle-analysis.txt
          echo "## Bundle Analysis Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          tail -n 20 bundle-analysis.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      
      - name: Upload bundle stats
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: |
            dist/*.js
            dist/*.css
            bundle-analysis.txt
          retention-days: 7
      
      - name: Comment PR with size info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Get file sizes
            const jsSize = fs.statSync('dist/cookie-banner.min.js').size;
            const cssSize = fs.statSync('dist/banner.css').size;
            
            // Format sizes
            const formatSize = (bytes) => {
              if (bytes < 1024) return bytes + ' B';
              if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(2) + ' KB';
              return (bytes / (1024 * 1024)).toFixed(2) + ' MB';
            };
            
            const comment = `### 📦 Bundle Size Report
            
            | File | Size |
            |------|------|
            | cookie-banner.min.js | ${formatSize(jsSize)} |
            | banner.css | ${formatSize(cssSize)} |
            | **Total** | **${formatSize(jsSize + cssSize)}** |
            
            All bundle sizes are within configured limits ✅`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });